/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SitzRouteImport } from './routes/sitz'
import { Route as SoloRouteImport } from './routes/solo'
import { Route as TischRouteImport } from './routes/tisch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitzRoute = SitzRouteImport.update({
  id: '/sitz',
  path: '/sitz',
  getParentRoute: () => rootRouteImport,
} as any)
const SoloRoute = SoloRouteImport.update({
  id: '/solo',
  path: '/solo',
  getParentRoute: () => rootRouteImport,
} as any)
const TischRoute = TischRouteImport.update({
  id: '/tisch',
  path: '/tisch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitz': typeof SitzRoute
  '/solo': typeof SoloRoute
  '/tisch': typeof TischRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitz': typeof SitzRoute
  '/solo': typeof SoloRoute
  '/tisch': typeof TischRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitz': typeof SitzRoute
  '/solo': typeof SoloRoute
  '/tisch': typeof TischRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sitz' | '/solo' | '/tisch'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sitz' | '/solo' | '/tisch'
  id: '__root__' | '/' | '/sitz' | '/solo' | '/tisch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitzRoute: typeof SitzRoute
  SoloRoute: typeof SoloRoute
  TischRoute: typeof TischRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitz': {
      id: '/sitz'
      path: '/sitz'
      fullPath: '/sitz'
      preLoaderRoute: typeof SitzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solo': {
      id: '/solo'
      path: '/solo'
      fullPath: '/solo'
      preLoaderRoute: typeof SoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tisch': {
      id: '/tisch'
      path: '/tisch'
      fullPath: '/tisch'
      preLoaderRoute: typeof TischRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitzRoute: SitzRoute,
  SoloRoute: SoloRoute,
  TischRoute: TischRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
